/** @format */

export const mockProperties = [
  {
    id: 1,
    category: "Apartment",
    image: "/path/to/image1.jpg",
    name: "Elegant Urban House",
    squareSpace: "2400",
    bedrooms: 4,
    bathrooms: 3,
    price: "450000",
    location: "Los Angeles, CA",
    rentPrice: "2250",
    description:
      "This 2400 sq ft elegant urban house boasts 4 bedrooms and 3 bathrooms, making it perfect for a family or shared living. Priced at $450,000, it's a gem in the heart of Los Angeles. With modern amenities and a stylish design, it reflects the vibrant urban lifestyle. The rental potential is excellent at $2250 per month, making it a great investment or a comfortable home.",
  },
  {
    id: 2,
    category: "Apartment",
    image: "/path/to/image2.jpg",
    name: "Cozy Country Cottage",
    squareSpace: "1800",
    bedrooms: 3,
    bathrooms: 2,
    price: "350000",
    location: "Austin, TX",
    rentPrice: "1750",
    description:
      "Nestled in Austin, this 1800 sq ft cozy country cottage features 3 bedrooms and 2 bathrooms. Priced at $350,000, it offers a charming retreat with a warm, inviting atmosphere. The cottage combines rustic charm with modern comforts, ideal for those seeking a peaceful living space. It's available for rent at $1750 per month, providing an attractive option for renters seeking tranquility.",
  },
  {
    id: 3,
    category: "Apartment",
    image: "/path/to/image3.jpg",
    name: "Luxurious Villa",
    squareSpace: "5000",
    bedrooms: 5,
    bathrooms: 4,
    price: "950000",
    location: "Miami, FL",
    rentPrice: "4750",
    description:
      "This luxurious villa in Miami, spanning 5000 sq ft, is the epitome of opulence with 5 bedrooms and 4 bathrooms. Its market price of $950,000 reflects its premium features and exquisite design. Ideal for high-end living or as a vacation home, it offers an unparalleled lifestyle. The rent price of $4750 per month makes it a lucrative option for those seeking luxury rentals.",
  },
  {
    id: 4,
    category: "Apartment",
    image: "/path/to/image4.jpg",
    name: "Modern Downtown Flat",
    squareSpace: "1100",
    bedrooms: 2,
    bathrooms: 2,
    price: "300000",
    location: "New York, NY",
    rentPrice: "1800",
    description:
      "In the heart of New York City, this modern downtown flat covers 1100 sq ft. It has 2 bedrooms and 2 bathrooms, and is priced at $300,000. Perfect for urban dwellers, it offers a contemporary living space with easy access to city amenities. The rental price of $1800 per month makes it an attractive choice for young professionals or couples.",
  },
  {
    id: 5,
    category: "Apartment",
    image: "/path/to/image5.jpg",
    name: "Charming Bungalow",
    squareSpace: "1300",
    bedrooms: 3,
    bathrooms: 1,
    price: "220000",
    location: "Seattle, WA",
    rentPrice: "1100",
    description:
      "This 1300 sq ft charming bungalow in Seattle features 3 bedrooms and 1 bathroom. With a selling price of $220,000, it presents a cozy and affordable living option. It's perfect for small families or individuals seeking a blend of comfort and simplicity. Available for rent at $1100 per month, it's a great deal for those looking for a budget-friendly yet quaint home.",
  },
  {
    id: 6,
    category: "Apartment",
    image: "/path/to/image6.jpg",
    name: "Spacious Suburban Home",
    squareSpace: "3200",
    bedrooms: 4,
    bathrooms: 3,
    price: "480000",
    location: "Chicago, IL",
    rentPrice: "2400",
    description:
      "Located in a serene suburb of Chicago, this spacious home spans 3200 sq ft and includes 4 bedrooms and 3 bathrooms. Priced at $480,000, it is ideal for families seeking a blend of comfort and space. The neighborhood offers a perfect balance between peaceful suburban life and easy access to city amenities. With a rental price of $2400 per month, it's an attractive option for long-term renters.",
  },
  {
    id: 7,
    category: "Townhome",
    image: "/path/to/image7.jpg",
    name: "Beachfront Condo",
    squareSpace: "900",
    bedrooms: 1,
    bathrooms: 1,
    price: "270000",
    location: "San Diego, CA",
    rentPrice: "1350",
    description:
      "This beachfront condo in San Diego offers breathtaking ocean views. Covering 900 sq ft, it includes 1 bedroom and 1 bathroom, making it perfect for individuals or couples. The asking price is $270,000, a great value for a property with such stunning vistas. Ideal for those seeking a relaxed, beachside lifestyle, it can also be rented for $1350 per month, appealing to vacation renters and locals alike.",
  },
  {
    id: 8,
    category: "Offices",
    image: "/path/to/image8.jpg",
    name: "Classic Colonial House",
    squareSpace: "3600",
    bedrooms: 4,
    bathrooms: 3,
    price: "600000",
    location: "Boston, MA",
    rentPrice: "3000",
    description:
      "This classic colonial house in Boston, covering 3600 sq ft, includes 4 bedrooms and 3 bathrooms. With a price tag of $600,000, it combines historical charm with modern amenities. Perfect for families or professionals seeking a distinguished residence with character. The rental potential is significant at $3000 per month, ideal for those looking to invest in a property with enduring appeal.",
  },
  {
    id: 9,
    category: "Apartment",
    image: "/path/to/image9.jpg",
    name: "Contemporary Loft",
    squareSpace: "2000",
    bedrooms: 2,
    bathrooms: 2,
    price: "750000",
    location: "San Francisco, CA",
    rentPrice: "4500",
    description:
      "In the vibrant heart of San Francisco, this contemporary loft covers 2000 sq ft and features 2 bedrooms and 2 bathrooms. Priced at $750,000, it offers a stylish, modern living space in one of the city's most sought-after areas. Ideal for urbanites, it provides a luxurious and convenient lifestyle. The rental price of $4500 per month reflects its premium location and modern amenities.",
  },
  {
    id: 10,
    category: "Apartment",
    image: "/path/to/image10.jpg",
    name: "Rustic Farmhouse",
    squareSpace: "4000",
    bedrooms: 5,
    bathrooms: 4,
    price: "800000",
    location: "Nashville, TN",
    rentPrice: "4000",
    description:
      "This rustic farmhouse, nestled in Nashville, spans 4000 sq ft and boasts 5 bedrooms and 4 bathrooms. With a selling price of $800,000, it offers a unique blend of rustic charm and modern comfort. Ideal for those seeking a spacious, country-style living environment. It is also available for rent at $4000 per month, making it an attractive option for families or groups who cherish the rustic aesthetic.",
  },
];
